# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1


orbs:
  node: circleci/node@5.0.3


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - node/install-packages:
          with-cache: true 
          cache-only-lockfile: true 
          include-branch-in-cache-key: true 
          check-cache: always 
          pkg-manager: yarn-berry 

workflows:
  example-workflow:
    jobs:
      - example-job
